### ISSUE TITLE
when gateway goes offline there is a flood of warning messages logged

### ISSUE THREAD

**Issue by cameronbraid** [zeebe-io/spring-zeebe#103]
```
01:05:17.886   257996 W io.zeebe.client.job.poller [grpc-default-executor-2] Failed to activated jobs for worker webapp and job type x.y
io.grpc.StatusRuntimeException: UNAVAILABLE: no healthy upstream
        at io.grpc.Status.asRuntimeException(Status.java:533)
        at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:453)
        at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:426)
        at io.grpc.internal.ClientCallImpl.access$500(ClientCallImpl.java:66)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:689)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$900(ClientCallImpl.java:577)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:751)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:740)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

I mean like 30k lines of log messages in 20 seconds

Can this be reduced ?  Can there be an exponential delay based retry ?

**Comment by cameronbraid** [comment]
This has become a more seriois issue if we have temporary connection issues with the gateway

Have seen this in production with 200k + log lines being logged.

is there a way to throttle this ?

**Comment by jwulf** [comment]
Is this against a self-hosted Zeebe gateway or Camunda Cloud?

**Comment by berndruecker** [comment]
@cameronbraid I close this for now - but feel free to reopen if you still face issues. Ideally you could provide a very specific scenario how to reproduce
