### ISSUE TITLE
IllegalAccessException while calling worker

### ISSUE THREAD

**Issue by shineships** [zeebe-io/spring-zeebe#110]
We are facing following error when a worker is called after starting the workflow
Environment details: 
Amazon EKS version 1.18
Zeebe 0.24.2 , can reproduce same issue with 0.25.3
Zeebe worker is in a spring boot application : spring-zeebe-starter 0.24.0

java.lang.RuntimeException: Failed to invoke method: importPromFile
	at io.zeebe.spring.client.bean.MethodInfo.invoke(MethodInfo.java:41)
	at io.zeebe.spring.client.config.processor.ZeebeWorkerPostProcessor.lambda$null$1(ZeebeWorkerPostProcessor.java:50)
	at io.zeebe.spring.client.config.processor.ZeebeWorkerPostProcessor$$Lambda$1221/0000000000000000.handle(Unknown Source)
	at io.zeebe.client.impl.worker.JobRunnableFactory.executeJob(JobRunnableFactory.java:44)
	at io.zeebe.client.impl.worker.JobRunnableFactory.lambda$create$0(JobRunnableFactory.java:39)
	at io.zeebe.client.impl.worker.JobRunnableFactory$$Lambda$1713/00000000801194C0.run(Unknown Source)
	at io.grpc.Context$1.run(Context.java:595)
	at io.grpc.Context$1.run(Context.java:595)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalAccessException: class io.zeebe.spring.client.bean.MethodInfo cannot access a member of class com.assentis.oc2.contentmanagement.workflow.ImportWorkers with modifiers "public"
	at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Unknown Source)
	at java.base/java.lang.reflect.AccessibleObject.checkAccess(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at io.zeebe.spring.client.bean.MethodInfo.invoke(MethodInfo.java:31)
	... 13 more

**Comment by berndruecker** [comment]
Hi @shineships - is this reproducible? Can you provide a test case for it?

Looks like the "handle" method of your own handling code is not accessible - com.assentis.oc2.contentmanagement.workflow.ImportWorkers is your class - right? Can you provide the sources here?
