### ISSUE TITLE
OpenJDK 12 and maven 3.6.1 failing to build the projects

### ISSUE THREAD

**Issue by salaboy** [zeebe-io/spring-zeebe#65]
Running 
```
mvn clean install
```

On the root of the repository fails with:

```
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:513)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:525)
Caused by: java.lang.RuntimeException: Class java/util/UUID could not be instrumented.
	at org.jacoco.agent.rt.internal_8ff85ea.core.runtime.ModifiedSystemClassRuntime.createFor(ModifiedSystemClassRuntime.java:140)
	at org.jacoco.agent.rt.internal_8ff85ea.core.runtime.ModifiedSystemClassRuntime.createFor(ModifiedSystemClassRuntime.java:101)
	at org.jacoco.agent.rt.internal_8ff85ea.PreMain.createRuntime(PreMain.java:55)
	at org.jacoco.agent.rt.internal_8ff85ea.PreMain.premain(PreMain.java:47)
	... 6 more
Caused by: java.lang.NoSuchFieldException: $jacocoAccess
	at java.base/java.lang.Class.getField(Class.java:2004)
	at org.jacoco.agent.rt.internal_8ff85ea.core.runtime.ModifiedSystemClassRuntime.createFor(ModifiedSystemClassRuntime.java:138)
	... 9 more
FATAL ERROR in native method: processing of -javaagent failed
/bin/sh: line 1: 43604 Abort trap: 6           /Library/Java/JavaVirtualMachines/adoptopenjdk-12.0.2.jdk/Contents/Home/bin/java -javaagent:/Users/salaboy/.m2/repository/org/jacoco/org.jacoco.agent/0.7.9/org.jacoco.agent-0.7.9-runtime.jar=destfile=/Users/salaboy/code/myforks/spring-zeebe/util/target/jacoco.exec -jar /Users/salaboy/code/myforks/spring-zeebe/util/target/surefire/surefirebooter12013810647460814714.jar /Users/salaboy/code/myforks/spring-zeebe/util/target/surefire/surefire6410680655165531208tmp /Users/salaboy/code/myforks/spring-zeebe/util/target/surefire/surefire_015604287260760055526tmp

Results :

Tests run: 0, Failures: 0, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for pom/spring-zeebe 0.7.0-SNAPSHOT:
[INFO] 
[INFO] pom/spring-zeebe ................................... SUCCESS [  0.913 s]
[INFO] test/spring-zeebe-test ............................. SUCCESS [  0.871 s]
[INFO] lib/spring-zeebe-util .............................. FAILURE [  1.548 s]


```

I am using the following versions, which seems to be the defaults for maven and OpenJDK while using brew in Mac

```
Apache Maven 3.6.1 (d66c9c0b3152b2e69ee9bac180bb8fcc8e6af555; 2019-04-04T21:00:29+02:00)
Maven home: /usr/local/Cellar/maven/3.6.1/libexec
Java version: 12.0.2, vendor: AdoptOpenJDK, runtime: /Library/Java/JavaVirtualMachines/adoptopenjdk-12.0.2.jdk/Contents/Home
Default locale: en_GB, platform encoding: UTF-8
OS name: "mac os x", version: "10.14.6", arch: "x86_64", family: "mac"
```

It definitely seems to be related to the jococo version used in the root pom:
```
<plugin>
        <groupId>org.jacoco</groupId>
        <artifactId>jacoco-maven-plugin</artifactId>
        <version>0.7.9</version>
        <executions>
          <execution>
            <goals>
              <goal>prepare-agent</goal>
            </goals>
          </execution>
          <execution>
            <id>report</id>
            <phase>test</phase>
            <goals>
              <goal>report</goal>
            </goals>
          </execution>
        </executions>

```

Version 0.8.4 is already available in maven central: https://search.maven.org/artifact/org.jacoco/jacoco-maven-plugin/0.8.4/maven-plugin

**Comment by Zelldon** [comment]
Hey @salaboy we saw lately some problems with AdoptOpenJDK for example: https://forum.zeebe.io/t/timeout-on-zeebe-deploy-command/623/10?u=zelldon and https://github.com/zeebe-io/zeebe/issues/2961

Could you please verify if you have the same issues with a different vendor?

Greets
Chris

**Comment by salaboy** [comment]
It looks like the same problem.. I am with AdoptOpenJDK as well. Java version: 12.0.2, vendor: AdoptOpenJDK, I am happy to close if you already have another issue to track it down

**Comment by salaboy** [comment]
I am closing this issue as I managed to run it in the end
